# Generated by Django 4.2.1 on 2023-11-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile-pic/')),
                ('banner', models.ImageField(null=True, upload_to='channel-banner/')),
                ('sub_count', models.IntegerField(default=0)),
                ('tag', models.CharField(null=True, unique=True)),
                ('active_channel', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL)),
                ('subscriptions', models.ManyToManyField(blank=True, to='youtube.channel')),
            ],
        ),
    ]
